/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as billboard from "../billboard";
import type * as category from "../category";
import type * as checkout from "../checkout";
import type * as collection from "../collection";
import type * as comment from "../comment";
import type * as music from "../music";
import type * as musicBackground from "../musicBackground";
import type * as order from "../order";
import type * as post from "../post";
import type * as product from "../product";
import type * as review from "../review";
import type * as voucher from "../voucher";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  billboard: typeof billboard;
  category: typeof category;
  checkout: typeof checkout;
  collection: typeof collection;
  comment: typeof comment;
  music: typeof music;
  musicBackground: typeof musicBackground;
  order: typeof order;
  post: typeof post;
  product: typeof product;
  review: typeof review;
  voucher: typeof voucher;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
